import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Container from '../components/Container';
import RecentActivity from '../components/RecentActivity';
import postAPI from '../apis/posts';

/**
 *
 * TODO:
 * 1. Make this static site using static props and Initial Activities should come from Page props
 * 2. Add a new page for creating a new post
 * 3. More should come from the API
 *
 */

const Home: NextPage = () => {
  const [blogs, setBlogs] = useState([]);
  const [loading, setLoading] = useState(false);

  const fetchBlogs = async () => {
    setLoading(true);
    try {
      const blogs = await postAPI.getPosts({
        page: 1,
      });

      console.log(blogs);

      setBlogs(blogs.posts);
    } catch (err) {}
    setLoading(false);
  };

  useEffect(() => {
    fetchBlogs();
  }, []);

  const _renderTopFivePosts = () => {
    return (
      <div className="grid lg:grid-cols-5 sm:grid-cols-3 md:grid-col-3 gap-10">
        {blogs.map((blog: any, k) => (
          <Link key={k} href={`post/${blog.slug}`}>
            <div className="shadow-md rounded-lg cursor-pointer hover:shadow-xl transition">
              <div className="p-2 mt-2">
                <div className="text-lg font-semibold">{blog.title}</div>
                <div className="text-sm font-semibold">{blog.author}</div>
                <div className="text-sm font-normal">{blog.summary}</div>
              </div>
            </div>
          </Link>
        ))}
      </div>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Amruth&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading && <div>Loading...</div>}

      {!loading && (
        <main className={'my-3'}>
          <Container heading="Top 5 most visited posts">
            {_renderTopFivePosts()}
          </Container>

          <RecentActivity />
        </main>
      )}
    </div>
  );
};

export default Home;
