import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Container from '../../components/Container';
import RecentActivity from '../../components/RecentActvity';

/**
 *
 * TODO:
 * 1. Make this static site using static props
 * 2. Add a new page for creating a new post
 *
 */

const PostPage: NextPage = () => {
  const [blogs, setBlogs] = useState([]);
  const [loading, setLoading] = useState(false);

  const fetchBlogs = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/blogs');
      const data = await res.json();
      setBlogs(data);
    } catch (err) {}
    setLoading(false);
  };

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await fetch(
        'https://xiuyf3nzxl.execute-api.ap-south-1.amazonaws.com/Prod/hello/'
      );
      const data = await res.json();
      console.log(data);
    } catch (err) {}
    setLoading(false);
  };

  useEffect(() => {
    fetchBlogs();
    fetchData();
  }, []);

  const _renderTopFivePosts = () => {
    return (
      <div className="grid lg:grid-cols-5 sm:grid-cols-3 md:grid-col-3 gap-10">
        {blogs.map((blog: any, k) => (
          <Link key={k} href={`post/${blog.slug}`}>
            <div className="shadow-md rounded-lg cursor-pointer hover:shadow-xl transition">
              <Image
                src={blog.image}
                alt="Landscape picture"
                width={100}
                height={100}
                layout="responsive"
              />
              <div className="p-2 mt-2">
                <div className="text-lg font-semibold">{blog.title}</div>
                <div className="text-sm font-semibold">{blog.author}</div>
                <div className="text-sm font-normal">{blog.summary}</div>
              </div>
            </div>
          </Link>
        ))}
      </div>
    );
  };

  return (
    <div>
      <Head>
        <title>Amruth&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading && <div>Loading...</div>}

      {!loading && (
        <main className={'my-3'}>
          <Container heading="Top 5 most visited posts">
            {_renderTopFivePosts()}
          </Container>
        </main>
      )}
    </div>
  );
};

// export async function getStaticProps({ params }) {
//   let result = await getProductsByproductLink({
//     productLink: params.product_id,
//   });

//   let config = result.config;
//   let product = result.product;

//   let basePrice =
//     product.basePrice - (product.basePrice * product.discountPercentage) / 100;
//   product.basePrice = basePrice;

//   return {
//     props: { productDetails: product, config: config || [] },
//     revalidate: 60,
//   };
// }

// export async function getStaticPaths() {
//   let paths = await fetch(process.env.NEXT_PUBLIC_API + '/admin/products/all')
//     .then((res) => res.json())
//     .then((res) => {
//       return res?.categories?.map((product) => ({
//         params: { product_id: product.productLink },
//       }));
//     });
//   return {
//     paths: paths || [],
//     fallback: true,
//   };
// }

export default PostPage;
