import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const _renderTopFivePosts = () => {
    return (
      <div>
        {/* Render Top 5 most visited posts */}
        <div>
          <h1>Top 5 most visited posts</h1>
        </div>
      </div>
    );
  };

  const _renderActivity = () => {
    return <div>{/* Render Top 5 most visited posts */}</div>;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'text-center'}>
        <h1 className="text-4xl font-bold">Welcome to Next.js!</h1>
      </main>
    </div>
  );
};

export default Home;
